steps:
  # Docker imajını oluşturma adımı
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-app', '.']

  # Oluşturulan Docker imajını Container Registry'ye yükleme adımı
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-app']

images:
  # Oluşturulan imajın nerede kullanılacağı belirtilir
  - 'gcr.io/$PROJECT_ID/my-app'
